import Head from 'next/head'
import React, { ReactNode } from 'react'

export interface IPrimarylayout {
  children: ReactNode
}

const PrimaryLayout = ({ children }: IPrimarylayout) => {
  return (
    <>
      <Head>
        <title>Next Starterkit</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>{children}</main>
    </>
  )
}

export default PrimaryLayout
