import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Next js starter-kit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main 
        className='flex min-w-full justify-center '
      >
        <p className='text-2xl px-2'>next js starter by tri</p>
      </main>
    </>
  )
}
