import PrimaryLayout from '@/components/layouts/primary/PrimaryLayout'
import Header from '@/components/section/Header/Header'
import Head from 'next/head'
import { NextPageWithLayout } from './page'

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Next Starterkit</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className=' flex justify-center '>lorem1000</div>
    </>
  )
}

export default Home

Home.getLayout = (page) => {
  return (
    <PrimaryLayout>
      <Header />
      {page}
    </PrimaryLayout>
  )
}
